### ISSUE TITLE
Only showing one Aim-map stat graph

### ISSUE THREAD

**Issue by Celerone** [andersfischernielsen/KovaaK-Visualizer#1]
Hello,

Very nice program even if it is not properly working for me, it only shows one of my played aim maps as a graph. I also get an module error from "seaborn", so it could even be my fault. 

Error if nor my fault:
seaborn\algorithms.py:86: RankWarning: Polyfit may be poorly conditioned
  boot_dist.append(f(*sample, **func_kwargs))

**Comment by andersfischernielsen** [comment]
That's a normal warning from seaborn when using polynomial plots. 
Do you have data for all the maps you have played in the `stats` folder?
